name: madrid_bike
description: A new Flutter project.
version: 1.0.0+1

author: Javier Elizaga <javier.elizaga@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_map: ^0.1.4
  flutter_location: ^0.0.3
  http: ^0.12.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

flutter:
  uses-material-design: true
